### ISSUE TITLE
split in_memory module like on_disk 

### ISSUE THREAD

**Issue by ZENOTME** [icelake-io/icelake#106]
I find that in_memory.rs is so long, do we consider to split into manifest_file, manifest_list like on_disk?

cc @liurenjie1024 @Xuanwo

**Comment by Xuanwo** [comment]
Is this issue preventing us from adding a new feature? If not, I would prefer to address it during the v0.1 polishing stage.

**Comment by ZENOTME** [comment]
I think not yet. Let's address it during the v0.1 polishing stage.

**Comment by Xuanwo** [comment]
Closing for https://github.com/icelake-io/icelake/issues/279
