### ISSUE TITLE
Tracking: Support partition write

### ISSUE THREAD

**Issue by ZENOTME** [icelake-io/icelake#114]
> BTW, do we prepare to support partition in 0.1 veriosn? It seems the whole API can build without partition.
>> Yes, it's necessary for practical use.

As discussed, support patition write is important. To support it, we need:
- [x] add partition field in data file 
- [x] support partition writer #153
- [ ] #102

**Comment by liurenjie1024** [comment]
Should we close this now?

**Comment by ZENOTME** [comment]
We have not yet implemented partition summary. And partition sumary should implemented after  #138 completed.

**Comment by Xuanwo** [comment]
Closing for https://github.com/icelake-io/icelake/issues/279
