### ISSUE TITLE
discussion: use order_float instead of f32,f64

### ISSUE THREAD

**Issue by ZENOTME** [icelake-io/icelake#116]
To support partition write, we need something like `HashMap<StructValue,_>`.  So this means that we need to impl Eq for AnyValue. To do this, we need to replace f32, f64 to order_float. (e.g. https://crates.io/crates/ordered-float)

As https://internals.rust-lang.org/t/f32-f64-should-implement-hash/5436/33#:~:text=If%20you%20want%20to%20have%20a%20content%20hash%20of%20a%20struct%20that%20includes%20floats says, to support Hash for the struct, we also can use serde. But I guess there may be other scenes we need Eq.

**Comment by ZENOTME** [comment]
cc @liurenjie1024 @Xuanwo

**Comment by Xuanwo** [comment]
I'm open with using `order_float`. But here are some edge cases to take care:

- The order: [spec said](https://iceberg.apache.org/spec/) we need to use -NaN < -Infinity < -value < -0 < 0 < value < Infinity < NaN.
- The hash: iceberg has hash specs for float value that: `hashLong(doubleToLongBits(double(v))`

Maybe we should do something extra here instead of store `StructValue` in hashmap directly.

**Comment by ZENOTME** [comment]
There are two problem in https://crates.io/crates/ordered-float 
1. -0 == +0
2. it don't have concept of -nan

I guess the only solve way is to maintain our own ordered_float.

**Comment by Xuanwo** [comment]
> I guess the only solve way is to maintain our own ordered_float.

Maybe it's easier to implement `Hash` and `Eq` by our own.

**Comment by ZENOTME** [comment]
> Maybe it's easier to implement Hash and Eq by our own.

Do you means that implement the custom behaviour in PrimitiveValue🤔, like 

```
impl<T: Float> Ord for PrimitiveValue<T> {
    fn cmp(&self, other: &Self) -> Ordering {
        match (self,other) => {
            (Float(l),Float(r)) => {
                // custom behaviour
            }
        } 
    }
}
```

**Comment by Xuanwo** [comment]
Closing for https://github.com/icelake-io/icelake/issues/279
