### ISSUE TITLE
Supports rest catalog.

### ISSUE THREAD

**Issue by liurenjie1024** [icelake-io/icelake#120]
The current implementation only supports filesystem catalog. In production, jdbc/hive metastore catalogs are widely used. To support them, we need to support rest catalog so that we don't need to interact with them directly.

**Comment by Xuanwo** [comment]
> Personally I prefer to keep them in repo to simplify whole thing, how do you guys think?

I perfer to keep them so that our users don't need to generate again.

**Comment by ZENOTME** [comment]
+1. Sounds reasonable for me.

**Comment by nooberfsh** [comment]
Hi, Our team are experimenting Trino + Iceberg with [Nessie Catalog](https://projectnessie.org/) (can be replaced with rest catalog), the query experience is good.  The missing part is data ingestion, we want to use `icelake` to ingest data to our lakehouse, the missing rest catalog support prevent us from doing so.
So what's the status about this?
BTW: `icelake` is a great project.

**Comment by liurenjie1024** [comment]
We have plans to support this, due to the schedule, maybe one month later we will start to implement it.

**Comment by liurenjie1024** [comment]
Tracked in #172
