### ISSUE TITLE
 discussion: let Table can be clone

### ISSUE THREAD

**Issue by ZENOTME** [icelake-io/icelake#125]
In risingwave sink, the sink own the table. We create writer or coordinator using table in sink. We need commit in writer or coordinator which means that we also need own table in writer and coordinator. 

<img width="937" alt="image" src="https://github.com/icelake-io/icelake/assets/43447882/5378f58e-f3fe-4f8d-8bb7-ef87aa6cf8ef">

cc @liurenjie1024 @Xuanwo

**Comment by Xuanwo** [comment]
Perhaps the sink could store all configuration needed to create a new table, instead of relying on the current state of the `Table`.
