### ISSUE TITLE
feat: support binary single-value serialization and deserialization.

### ISSUE THREAD

**Issue by RinChanNOWWW** [icelake-io/icelake#138]
There are many binary value fields in `DataFile`, such as `lower_bounds`, `upper_bounds`, ... However, there aren't serializers and deserializers for them.

Spec:

- Binary single-value serialization: https://iceberg.apache.org/spec/#binary-single-value-serialization

**Comment by Xuanwo** [comment]
Closing for https://github.com/icelake-io/icelake/issues/279
