### ISSUE TITLE
Friendly write test framework

### ISSUE THREAD

**Issue by ZENOTME** [icelake-io/icelake#168]
For now our test for write is hard extend to test kinds of table. The schema is hard-code.

So I propose a way to make test more easily to extend.

We can describe the test in yaml file like following: 
```
schema:
	init_sql:
		CREATE SCHEMA IF NOT EXISTS s1

src:  
	name: t1
	root: demo/s1/t1
	init_sql: 
		DROP TABLE IF EXISTS s1.t1,
        CREATE TABLE s1.t1
        (
            id long,
            v_int int,
            v_long long,
            v_float float,
            v_double double,
            v_varchar string,
            v_bool boolean,
            v_date date,
            v_timestamp timestamp,
            v_decimal decimal(36, 10),
            v_ts_ntz timestamp_ntz
        ) USING iceberg
        TBLPROPERTIES ('format-version'='2');


dst:
	name: tmp
	root: demo/s1/tmp
	init_sql: 
		DROP TABLE IF EXISTS s1.tmp,
        CREATE TABLE s1.tmp
        (
            id long,
            v_int int,
            v_long long,
            v_float float,
            v_double double,
            v_varchar string,
            v_bool boolean,
            v_date date,
            v_timestamp timestamp,
            v_decimal decimal(36, 10),
            v_ts_ntz timestamp_ntz
        ) USING iceberg
        TBLPROPERTIES ('format-version'='2');

write_data:
	schema: long,int,float,double,string,boolean,date,timestamp ..
	data:
		1,1,1000,1.1,1.11,1-1,true,2022-11-01,2022-11-01 11:03:02.123456+04:00,389.11111,2022-11-01 11:03:02.123456
		2,2,2000,2.2,2.22,2-2,false,2022-11-02,2022-11-02 11:03:02.123456+04:00,389.2222,2022-11-02 11:03:02.123456
		3,3,3000,3.3,3.33,3-3,true,2022-11-03,2022-11-03 11:03:02.123456+04:00,389.3333,2022-11-03 11:03:02.123456
		4,4,4000,4.4,4.44,4-4,false,2022-11-04,2022-11-04 11:04:02.123456+04:00,389.4444,2022-11-04 11:04:02.123456
		5,5,5000,5.5,5.55,5-5,true,2022-11-05,2022-11-05 11:05:02.123456+04:00,389.5555,2022-11-05 11:05:02.123456

query_sql: 
		select * from s1.t1;
		select * from s1.tmp;

query_sql:
		select * from s1.t1.partitions;
		select * from s1.tmp.partitions;
```
1. In the init phase, the test framework will execute the init sql.
2. In the write phase, the test framework will parse the schema and write data into t1 and tmp seperatly using icelake and other client(like spark sql).
3. In the check phase, the test framework will execute two sql and check whether the output is same.

The benifit of this way:
1. support kinds of schema 
2. describe the whole test process in a external file.

**Comment by ZENOTME** [comment]
@liurenjie1024 @Xuanwo Do you have any suggestion?

**Comment by liurenjie1024** [comment]
Generally LGTM. But the src and dst tables only differs in table name, I think we don't need two create table statements?

**Comment by liurenjie1024** [comment]
I think the create table statement can by generated by fields? Since we need to know the record batch schema when reading from csv.

**Comment by ZENOTME** [comment]
> I think the create table statement can by generated by fields? Since we need to know the record batch schema when reading from csv.

> Generally LGTM. But the src and dst tables only differs in table name, I think we don't need two create table statements?

Yes, We can simplify the config like following and generated the create table sql. 

```
schema: 
    long,int,float,double,string,boolean,date,timestamp ..
data:
    1,1,1000,1.1,1.11,1-1,true,2022-11-01,2022-11-01 11:03:02.123456+04:00,389.11111,2022-11-01 11:03:02.123456
    2,2,2000,2.2,2.22,2-2,false,2022-11-02,2022-11-02 11:03:02.123456+04:00,389.2222,2022-11-02 11:03:02.123456
    3,3,3000,3.3,3.33,3-3,true,2022-11-03,2022-11-03 11:03:02.123456+04:00,389.3333,2022-11-03 11:03:02.123456
    4,4,4000,4.4,4.44,4-4,false,2022-11-04,2022-11-04 11:04:02.123456+04:00,389.4444,2022-11-04 11:04:02.123456
    5,5,5000,5.5,5.55,5-5,true,2022-11-05,2022-11-05 11:05:02.123456+04:00,389.5555,2022-11-05 11:05:02.123456

query_sql: 
		select * from s1.t1;
		select * from s1.tmp;

query_sql:
		select * from s1.t1.partitions;
		select * from s1.tmp.partitions;
```

**Comment by liurenjie1024** [comment]
LGTM

**Comment by Xuanwo** [comment]
For examples:

```sql
statement ok
CREATE TABLE s1.t1
        (
            id long,
            v_int int,
            v_long long,
            v_float float,
            v_double double,
            v_varchar string,
            v_bool boolean,
            v_date date,
            v_timestamp timestamp,
            v_decimal decimal(36, 10),
            v_ts_ntz timestamp_ntz
        ) USING iceberg
        TBLPROPERTIES ('format-version'='2');

statement ok
insert into t values(1,1,1000,1.1,1.11,1-1,true,2022-11-01,2022-11-01 11:03:02.123456+04:00,389.11111,2022-11-01 11:03:02.123456)

query I
select * from t
----
1,1,1000,1.1,1.11,1-1,true,2022-11-01,2022-11-01 11:03:02.123456+04:00,389.11111,2022-11-01 11:03:02.123456
```

**Comment by liurenjie1024** [comment]
The original idea is from @ZENOTME that we want to simplify the testing setup process. That means the test process becomes:
1. we insert same data into iceberg with both icelake and spark sql, 
2. We query them using spark
3. We compare the results to ensure that should be same

That's why we need some yaml to help to setup data, including creating table, read data. But if we use pure sql for everything, that means when we execute sqls in icelake, we need to parse sql, translate plan, and execute them. This requires sql engine for it.

**Comment by liurenjie1024** [comment]
Generally, I think pure data-driven tests like sqllogictest is the correct way to do it. However currently we don't have integration with sql engines like datafusion, so it's difficult to achieve it now.

**Comment by Xuanwo** [comment]
Thanks for the explanation!

My last problem is can we use toml instead of yaml?

**Comment by liurenjie1024** [comment]
> Thanks for the explanation!
> 
> My last problem is can we use toml instead of yaml?

Both are ok to me, it's up to @ZENOTME

**Comment by ZENOTME** [comment]
> My last problem is can we use toml instead of yaml? 

Toml looks good to me. Actually yaml is just a example. 

> Generally, I think pure data-driven tests like sqllogictest is the correct way to do it. However currently we don't have integration with sql engines like datafusion, so it's difficult to achieve it now.

And I also agree with it's better if we can use datafusion and using sqllogictest to test. So let's keep this test framework as simple as possible then I can take a investigate how to integrate with datafusion later.
