### ISSUE TITLE
Incompatitable schema using apache-avro rust

### ISSUE THREAD

**Issue by ZENOTME** [icelake-io/icelake#174]
I try to support to write decimal in avro and find that there is incompatitablity using apache-avro rust schema directly.

In iceberg spec, the decimal represent in avro as:
```
{ 
  "type": "fixed",
  "size": minBytesRequired(P),
  "logicalType": "decimal",
  "precision": P,
  "scale": S 
}
```

But in Schema::Decimal in apache-avro rust, [the serialize way](https://github.com/apache/avro/blob/60796e5df4581589717cfa32952da792dec79b68/lang/rust/avro/src/schema.rs#L1818) will cause the type look like:
```
{ 
  "type": {
      "type": fixed,
      "size": minBytesRequired(P),
  },
  "logicalType": "decimal",
  "precision": P,
  "scale": S 
}
```
And it's incompatitable with the type spec in iceberg.

I have try to modify the serialize way in local and verify that it can work.
```
            Schema::Decimal(DecimalSchema {
                ref scale,
                ref precision,
                ref inner,
            }) => {
                let mut map = serializer.serialize_map(None)?;
                map.serialize_entry("type", "fixed")?;
                map.serialize_entry("name", "decimal_36_10")?;
                map.serialize_entry("size", &16)?;
                map.serialize_entry("logicalType", "decimal")?;
                map.serialize_entry("scale", scale)?;
                map.serialize_entry("precision", precision)?;
                map.end()
            }
```

There are seems no way provied by avro-rust to custom the serialize way. Apparently we can fork the avro-rust and modify it to make it work but this solution is not very well. Maybe we can have a communication wtih community of apache-avro rust.

**Comment by ZENOTME** [comment]
cc @liurenjie1024 @Xuanwo Any suggestion?

**Comment by liurenjie1024** [comment]
Where is this conversion used? I think when serializing in  avro schema approach, we should:
iceberg schema -> avro schema -> serialize

And do the reverse when doing deserializing?

**Comment by ZENOTME** [comment]
Sorry for unclear expression. I mean [the conversion](https://github.com/apache/avro/blob/60796e5df4581589717cfa32952da792dec79b68/lang/rust/avro/src/schema.rs#L1818) happend in avro schema -> serialize. It will serialize the decimal schema look like following:
```
{ 
  "type": {
      "type": fixed,
      "size": minBytesRequired(P),
  },
  "logicalType": "decimal",
  "precision": P,
  "scale": S 
}
```
But what we need is to serialize the decimal schema look like :
```
{ 
  "type": "fixed",
  "size": minBytesRequired(P),
  "logicalType": "decimal",
  "precision": P,
  "scale": S 
}
```
