### ISSUE TITLE
Consolidate configurations for catalog.

### ISSUE THREAD

**Issue by liurenjie1024** [icelake-io/icelake#201]
Currently we have configurations for catalog and table io. Their naming convention is not consistent, we need to figure out a way for the new name.

**Comment by liurenjie1024** [comment]
cc @Xuanwo @ZENOTME

**Comment by liurenjie1024** [comment]
My suggestion is as following:

1. All configurations should start with `iceberg`.
2. Catalog configurations should start with `catalog`. 
The configuration for rest catalog is:
```
iceberg.catalog.uri
iceberg.catalog.name
```
The configuration for filesystem catalogs:
```
iceberg.catalog.warehouse
```
3. Configuration for table configuration is:
```
iceberg.table.io.region
iceberg.table.io.endpoint
iceberg.table.io.access_key_id
iceberg.table.io.secret_access_key
iceberg.table.parquet_writer.enable_bloom_filter
iceberg.table.datafile.rows_per_file
```

**Comment by Xuanwo** [comment]
LGTM!

**Comment by ZENOTME** [comment]
LGTM!
