### ISSUE TITLE
Add simple integration with datafusion to speed up data driven tests.

### ISSUE THREAD

**Issue by liurenjie1024** [icelake-io/icelake#207]

**Comment by ZENOTME** [comment]
I'm glad to take this work if no one start it yet.

**Comment by Xuanwo** [comment]
Maybe we need https://github.com/apache/incubator-opendal/tree/main/integrations/object_store?

**Comment by liurenjie1024** [comment]
> I'm glad to take this work if no one start it yet.

Not yet. Welcome to do it. But it's better to propose a design before actual implementing it.

**Comment by Xuanwo** [comment]
Closing for https://github.com/icelake-io/icelake/issues/279
