### ISSUE TITLE
How to select the specific version arrow

### ISSUE THREAD

**Issue by ZENOTME** [icelake-io/icelake#221]
Hi, Can we select the specific version for the arrow crate?

e.g. 
select 46 for `arrow-array = { version = ">=46" }`

I try to import the icelake and it will always import the latest arrow-* 47 even there is the arrow-* 46 in project.

@Xuanwo

**Comment by Xuanwo** [comment]
> Can we select the specific version for the arrow crate?

How about using `cargo update -p arrow-xxx@46.0.0`?

**Comment by ZENOTME** [comment]
> How about using cargo update -p arrow-xxx@46.0.0?

Seems it doesn't work.
