### ISSUE TITLE
A new way to create writer

### ISSUE THREAD

**Issue by ZENOTME** [icelake-io/icelake#243]
## Problem

Hi, I find that now our writer design has some problems now:
1. The parameter has to pass top down. It makes the process of creating writer is tedious and couple. E.g: The delta writer use data file writer , position delete writer and equality delete writer. So `new` signature of delta need to accept the LocationGenerator for data file writer and another one for delete file writer. And we also need to pass TableConfig top down. In the future, we prepare to add metrics for kinds of writer, so we end up to pass metrics top down.
2. It's hard to combine kinds of writer, e.g. we have the `PartitionAppendOnlyWriter` and the `PartitionUpsertWriter`. We can't decouple the `PartitionWriter` and `FileWriter`(`AppendOnlyWriter` and `Upsert Writer`). 

## Target 

1. Make the process of creating writer is decouple. We don't need to pass kinds of parameters top down.
2. After creating them independently, we can combine them easily. E.g. combined partition writer with any file writer.

## Solution

I have think a new  API to create the writer, it modified from our original layer trait. Seems it can make combing and reusing the writer easier. 

```
#[async_trait]
pub trait FileAppender: Send + 'static {
    async fn write(&mut self, batch: RecordBatch) -> Result<()>;
    async fn close(&mut self) -> Result<Vec<DataFileBuilder>>;
}

pub trait FileAppenderLayer: Send + Sync + Clone + 'static {
    type R: FileAppender;
    fn compile( &mut self, schema: &SchemaRef) -> Result<()>;
    fn build(self) -> Result<Self::R>;
}

// Implementation Example of Rolling Writer 
#[derive(Clone)]
pub struct RollingWriterLayer {
    location_generator: Arc<FileLocationGenerator>,

    config: RollingWriterConfig,
    parquet_config: ParquetWriterConfig,
    operator: Operator,
    table_location: String,

    /// compiled
    arrow_schema: Option<SchemaRef>,
}

impl RollingWriterLayer {
    pub fn new(
        operator: Operator,
        table_location: String,
        location_generator: Arc<FileLocationGenerator>,
        config: RollingWriterConfig,
        parquet_config: ParquetWriterConfig,
    ) -> Self {
        Self {
            location_generator,
            config,
            parquet_config,
            operator: None,
            table_location: None,
            arrow_schema: None,
        }
    }
}

impl FileAppenderLayer for RollingWriterLayer {
    type R = RollingWriter;

    fn compile(
        &mut self,
        schema: &SchemaRef,
    ) -> Result<()> {
        self.arrow_schema = Some(schema.clone());
        Ok(())
    }

    fn build(self) -> Result<Self::R> {
        RollingWriter::try_new(
            self.operator.unwrap(),
            self.table_location.unwrap(),
            self.location_generator,
            self.arrow_schema.unwrap(),
            self.config,
            self.parquet_config,
        )
    }
}

```
The process of creating a writer has 3 steps:
1. Create the writer layer. In this step, we pass the parameter **this writer** need and it's decouple. We don't need to pass the parameter top down. Such as config and location generator.
2. Compile(May be Bind is more appropriate). In this step, we pass the schema top down so that we can reuse the rolling writer in different file writers. E.g. position delete writer can pass the `Schema<String,Int>` to it in compile step.
3. Build it to get the writer!

We can notice that the layer is `Clone` and which means that after compile, we can store it directly as a  `FileBuilder`. E.g in [sorted cache writer ](https://github.com/icelake-io/icelake/blob/b7712aed62b6142de6303c1cd9ad1c1c1d823109/icelake/src/io/file_writer/position_delete_writer.rs#L56)

Finally, we can find that it's easy to create and combine the writer use this API. It looks like, e.g.

```
let rolling_layer = RollingWriterLayer::new(rolling_config);
let rolling_metrics_layer = RollingMetricsLayer::new(rolling_layer);
let data_filer_layer = DataFileLayer::new(rolling_metrics_layer);
let partition_layer = PartitionLayer::new(data_filer_layer);
let shcema = table.current_schema();
let compiled_layer = partition_layer.compile(&schema);
let writer = complied_layer.build();
```

I have draft a PR #242 to try to implement this and find that it's successfully to rewrite all the writer I have in this way. 
( It has a little difference between the solution I describe above, but the key sights is same.

## More improvement

We can separate the layer into three kinds to guarantee the correctness.

- FileAppenderLayer : RollingWriterLayer
- FileWriterLayer: DataFIleWriterLayer, PositionDeleteWriterLayer, EqualityDeleteWriterLayer
- FunctionLayer: PartitionLayer, SortedCachedLayer

**Comment by ZENOTME** [comment]
cc @liurenjie1024  @Xuanwo

**Comment by liurenjie1024** [comment]
IIUC, the `FileAppenderLayer` is sth like file appender factory? I don't quite understand why we need a `compile` method here?

**Comment by ZENOTME** [comment]
Let's think about if we only have the `build(self,&Schema)`. Then everytime we need to pass the schema to the layer when we build. 

> We can notice that the layer is Clone and which means that after compile, we can store it directly as a FileBuilder. E.g in [sorted cache writer](https://github.com/icelake-io/icelake/blob/b7712aed62b6142de6303c1cd9ad1c1c1d823109/icelake/src/io/file_writer/position_delete_writer.rs#L56)

So in this SortedCacheWriter, I need to store the layer and schema. The compile phase is to separate this out, after compile, we only need to store the layer and don't need to store the schema.

**Comment by liurenjie1024** [comment]
> Let's think about if we only have the `build(self,&Schema)`. Then everytime we need to pass the schema to the layer when we build.
> 
> > We can notice that the layer is Clone and which means that after compile, we can store it directly as a FileBuilder. E.g in [sorted cache writer](https://github.com/icelake-io/icelake/blob/b7712aed62b6142de6303c1cd9ad1c1c1d823109/icelake/src/io/file_writer/position_delete_writer.rs#L56)
> 
> So in this SortedCacheWriter, I need to store the layer and schema. The compile phase is to separate this out, after compile, we only need to store the layer and don't need to store the schema. This also means that in SortedCacheWriter, it's totally decoupled with FileWriter, it doesn't need to take care of schema. It just takes care of the sort and cache.

So this is sth like init parameter of `FileAppenderLayer`? How about modifying it to following:
```
pub struct FileAppenderLayerInput {
 schema: SchemaRef,
  op: Operator 
}

pub trait FileAppenderLayer {
   type R: FileAppdner;
   
  fn init(input: FileAppenderLayerInput) -> Result<Self>;

  fn build(self) -> Result<Self::R>;
}
```

I think this way we don't need to maintain init state of concrete factory?

**Comment by ZENOTME** [comment]
>  fn init(input: FileAppenderLayerInput) -> Result<Self>;

Seems it can't be an init function like this.🤔 We want to create each layer independently which means that we should let the concrete factory implement their own new\init function. E.g.
```
// Create independently first. We need a custom `new` function. 
let rolling_layer = RollingLayer::new(rolling_config,rolling_metrics);
// And then combine it with other layers
let data_file_layer = DataFileLayer::new(rolling_layer, data_file_config, data_file_metrics)
```

**Comment by ZENOTME** [comment]
The `fn compile( &mut self, schema: &SchemaRef) -> Result<()>;` is werid to understand. 

The API is modifed to 
```
#[async_trait]
pub trait RecordBatchWriter: Send + 'static {
    async fn write(&mut self, batch: RecordBatch) -> Result<()>;
    async fn close(&mut self) -> Result<Vec<DataFileBuilder>>;
}

pub trait RecordBatchWriterBuilderLayer: Send + Sync + Clone + 'static {
    type R: RecordBatchWriter;
    fn build(self, schema: &Schema) -> Result<Self::R>;
}
```
Hope it be more easily to understand.

**Comment by Xuanwo** [comment]
I have question: How many struct will implement trait `RecordBatchWriter` (for example)?

**Comment by ZENOTME** [comment]
> I have a question: How many struct will implement trait RecordBatchWriter (for example)?

Every internal writer. E.g. DataFileWriter, DeltaWriter, PosistionDeleteWriter.

**Comment by ZENOTME** [comment]
I realize that using #[async_trait] to define writer trait may introduce overhead. maybe we need https://blog.rust-lang.org/inside-rust/2022/11/17/async-fn-in-trait-nightly.html

**Comment by liurenjie1024** [comment]
> I realize that using #[async_trait] to define writer trait may introduce overhead. maybe we need https://blog.rust-lang.org/inside-rust/2022/11/17/async-fn-in-trait-nightly.html

This requires nightly rust, and will be stable in recent release.

**Comment by liurenjie1024** [comment]
> We can achieve this without introducing any trait. Just need to reach the consensus that every writer has their own layer.

The problem without a trait is that you are depending on concrete type. This is not good for extensibility, for example, what if you want to support other formats such as orc in future.

**Comment by ZENOTME** [comment]
>This requires nightly rust, and will be stable in recent release.

Seem today. 🤣 https://releases.rs/docs/1.74.0/#:~:text=Released%20on%3A%2016%20November%2C%202023

**Comment by liurenjie1024** [comment]
> > This requires nightly rust, and will be stable in recent release.
> 
> Seem today. 🤣 https://releases.rs/docs/1.74.0/#:~:text=Released%20on%3A%2016%20November%2C%202023

Let's move.

**Comment by ZENOTME** [comment]
My bad. async fn in trait should be in 1.75.0 😭https://releases.rs/docs/1.75.0/#:~:text=Stabilize%20async%20fn%20and%20return%2Dposition%20impl%20Trait%20in%20trait%20(merged%2033%20days%20ago)

**Comment by ZENOTME** [comment]
We find the extra requirement I didn't realize before:
1. Builder trait to let config writer independently.
2. Writer can be combined flexibly.
3. Separate the writer into two layers to make the arch clean: 
    - iceberg writer: data file writer, position delete writer, equality delete writer, partition writer,...
    - file writer: rolling writer, parquet writer, orc writer 
   The file writer is the writer writes data actually. And the iceberg write is to provide more high-level functions based on them.
4. **We hope two layer both are extensible, user can custom their own writer in some layer and connect it to another layer.** E.g user can custom a new file writer rather than rolling writer and connect it to data file writer. Or custom a new iceberg writer such as filter writer and connect it to data file writer.
5. **For iceberg writer, the input should be extensible rather than only `RecordBatch`.** E.g the sort writer, it's the writer to accept input and cache it. When the cache num reaches the threshold, it will sort and flush them. If the upper layer only write a row one time, then it need to convert the row to `RecordBatch` every time. And the sort writer need to contact the `RecordBatch` when flush them. It's inefficient. 

To fulfill these requirements, I refine the design:
```
#[async_trait::async_trait]
pub trait WriterBuilder: Send + Sync + Clone + 'static {
    type R;
    async fn build(self, schema: &SchemaRef) -> Result<Self::R>;
}

#[async_trait::async_trait]
pub trait FileWriter: Send + 'static {
    type R: WriteResult;
    async fn write(&mut self, batch: RecordBatch) -> Result<()>;
    async fn close(&mut self) -> Result<Self::R>;
}

#[async_trait::async_trait]
pub trait IcebergWriter<I = RecordBatch>: Send + 'static {
    type R: WriteResult;
    async fn write(&mut self, input: I) -> Result<()>;
    async fn close(&mut self) -> Result<Self::R>;
}

pub trait WriteResult: Send + Sync + 'static + Default {
    fn with_content(self, content: crate::types::DataContentType) -> Self;
    fn with_equality_ids(self, equality_ids: Vec<i32>) -> Self;
    fn with_partition_value(self, partition_value: Option<StructValue>) -> Self;
    fn extend_res(&mut self, other: Self);
}

// The extra interface provided by a writer, we separate it out.
pub trait SingletonWriter {
    fn current_file(&self) -> String;
    fn current_row_num(&self) -> usize;
}

```

**Comment by liurenjie1024** [comment]
Generally I'm fine with this design, but I have some suggestions:
1. Since we have decided to separate writers to two layers, I think we also need to separate `WriterBuilder` into two different traits, e.g. we should add an extra `FileWriterBuilder` trait.
2. Also same for writer result. Although they look similar for now, it's not reasonable to mix them together, this will make api evolving difficult.
3. I think `IcebergWriter` is for single partition, right?

**Comment by ZENOTME** [comment]
> I think IcebergWriter is for single partition, right?

No, ParitionWriter is also an IcebergWriter. And it can be easily combined with other writers.

And I guess the trait can be modified like:
```
#[async_trait::async_trait]
pub trait FileWriterBuilder: Send + Sync + Clone + 'static {
    type R: FileWriter;
    async fn build(self, schema: &SchemaRef) -> Result<Self::R>;
}

#[async_trait::async_trait]
pub trait FileWriter: Send + 'static {
    type R: FileWriteResult;
    async fn write(&mut self, batch: RecordBatch) -> Result<()>;
    async fn close(&mut self) -> Result<Self::R>;
}

#[async_trait::async_trait]
pub trait IcebergWriterBuilder: Send + Sync + Clone + 'static {
    type R;
    async fn build(self, schema: &SchemaRef) -> Result<Self::R>;
}

#[async_trait::async_trait]
pub trait IcebergWriter<I = RecordBatch>: Send + 'static {
    type R: WriteResult;
    async fn write(&mut self, input: I) -> Result<()>;
    async fn close(&mut self) -> Result<Self::R>;
}

pub trait FileWriteResult: Send + Sync + 'static + Default {
  type R: WriteResult;
  fn convert(self) -> Self::R;
}

pub trait WriteResult: Send + Sync + 'static + Default {
    fn with_content(self, content: crate::types::DataContentType) -> Self;
    fn with_equality_ids(self, equality_ids: Vec<i32>) -> Self;
    fn with_partition_value(self, partition_value: Option<StructValue>) -> Self;
    fn extend_res(&mut self, other: Self);
}
```

**Comment by liurenjie1024** [comment]
Almost LGTM. Do we still need the trait `WriteResult`? I think simply two traits makes things more clear?

**Comment by ZENOTME** [comment]
> Do we still need the trait WriteResult? 

We need it because we need to modify the WriteResult when implement the `close` method in IcebergWriter trait. Like set the DataContentType.

**Comment by liurenjie1024** [comment]
> > Do we still need the trait WriteResult?
> 
> We need it because we need to modify the WriteResult when implement the `close` method in IcebergWriter trait. Like set the DataContentType.

I mean we should have two trait for `WriteResult`, `FileWriteResult`, rather than sharing one common trait?

**Comment by liurenjie1024** [comment]
Oh, sorry, I have some misunderstanding. LGTM

**Comment by ZENOTME** [comment]
Now we have the first complete implementation #242. And the creation process is flexible. We can extend any writer independently. 
```
async fn create_writer(
        &self,
    ) -> UpsertWrapperWriter<
        impl IcebergWriter<R = DeltaResult<Vec<DataFileBuilder>, Vec<DataFileBuilder>>>,
    > {
        let table = self.create_icelake_table().await;
        log::info!(
            "Real path of table is: {}",
            table.current_table_metadata().location
        );

        let paquet_writer_builder = table
            .writer_builder()
            .unwrap()
            .parquet_writer_builder(0)
            .unwrap();
        let rolling_writer_builder = table
            .writer_builder()
            .unwrap()
            .rolling_writer_builder(None, paquet_writer_builder)
            .unwrap();
        let data_file_writer_builder = DataFileWriterBuilder::new(rolling_writer_builder.clone());
        let equality_delete_writer_builder =
            EqualityDeleteWriterBuilder::new(rolling_writer_builder.clone(), vec![1, 2]);
        let position_delete_writer_builder =
            PositionDeleteWriterBuilder::new(rolling_writer_builder.clone(), None);
        let sorted_position_delete_writer_budiler =
            SortWriterBuilder::new(position_delete_writer_builder, 0, 100);
        let delta_writer = EqualityDeltaWriterBuilder::new(
            data_file_writer_builder,
            sorted_position_delete_writer_budiler,
            equality_delete_writer_builder,
            vec![1, 2],
            false,
        );
        let partition_writer_builder = table
            .writer_builder()
            .unwrap()
            .partition_writer_builder(delta_writer)
            .unwrap();
        UpsertWrapWriterBuilder::new(partition_writer_builder)
            .build(&table.current_arrow_schema().unwrap())
            .await
            .unwrap()
    }
```

But seems there are some problem:
1. create process is flexible but tedious. Maybe we can provide the higher level interface based on them. 
2. The return type may be urgly. Following complete type is 🥵  (Although this type can be infered by compiler
```
UpsertWrapperWriter<
         PartitionedWriter<
                  EqualityDeltaWriterBuilder<
                         DataFileWriterBuilder<RollingWriterBuilder<ParquetWriterBuilder>>, 
                         SortWriterBuilder<
                                 PositionDeleteInput, PositionDeleteWriterBuilder<RollingWriterBuilder<ParquetWriterBuilder>>>, 
                         EqualityDeleteWriterBuilder<RollingWriterBuilder<ParquetWriterBuilder>>>>>`
```
When user want to store this in a struct, they need to declare the complete name or use `Box<dyn>`. But seems it can't avoid if we want to make writer general.

I'm not sure whether there are better solution or it's just a trade-off we have to make. I'm glad to refine the design if you have better idea. cc @liurenjie1024  @Xuanwo

**Comment by liurenjie1024** [comment]
> 1. create process is flexible but tedious. Maybe we can provide the higher level interface based on them.

I think it's ok, we just need to provide some helper method to make the most frequently used ones easier to write.

> 2. The return type may be urgly. Following complete type is 🥵 (Although this type can be infered by compiler

I think for the outer most api, we should make it easy to for user. It would be better to wrap it in `Arc<dyn>`?

**Comment by Xuanwo** [comment]
> I think for the outer most api, we should make it easy to for user. It would be better to wrap it in `Arc<dyn>`?

Agreed. We shouldn't let users to play with generic parameters, as they could potentially create a writer instance and passing it around which means we should write the type down. Consider the case of databases: we will construct various interpreters/stages and perform transformations.

**Comment by liurenjie1024** [comment]
I think the outer most user api such as `RecordBatchWriter` can be object safe?

**Comment by ZENOTME** [comment]
Thanks! The following api can work
```
pub struct DeltaWriter {
    inner: Box<dyn IcebergWriter<R = DeltaResult<Vec<DataFileBuilder>, Vec<DataFileBuilder>>>>,
}

impl DeltaWriter {
    pub async fn write(&mut self, op: impl Into<Vec<i32>>, input: RecordBatch) -> Result<()> {
        let mut fields = input.schema().fields().to_vec();
        fields.push(Arc::new(Field::new(
            "",
            arrow_schema::DataType::Int32,
            false,
        )));

        let schema = Arc::new(arrow_schema::Schema::new(fields));

        let mut columns = input.columns().to_vec();
        columns.push(Arc::new(arrow_array::Int32Array::from(op.into())));

        let batch = RecordBatch::try_new(schema, columns).unwrap();

        self.inner.write(batch).await
    }

    pub async fn close(
        &mut self,
    ) -> Result<DeltaResult<Vec<DataFileBuilder>, Vec<DataFileBuilder>>> {
        self.inner.close().await
    }
}

pub struct RecordBatchWriter {
    inner: Box<dyn IcebergWriter<R = Vec<DataFileBuilder>>>,
}

impl RecordBatchWriter {
    pub async fn write(&mut self, input: RecordBatch) -> Result<()> {
        self.inner.write(input).await
    }

    pub async fn close(&mut self) -> Result<Vec<DataFileBuilder>> {
        self.inner.close().await
    }
}
```
> I think for the outer most api, we should make it easy to for user. It would be better to wrap it in Arc<dyn>?

We can't work on `Arc<dyn>` because we can't get `&mut` from it.

**Comment by liurenjie1024** [comment]
Is `DeltaWriter ` and `RecordBatchWriter` written in this approach can be `Send + Sync`?

**Comment by ZENOTME** [comment]
> Is DeltaWriter  and RecordBatchWriter written in this approach can be Send + Sync?

Send and Sync in Box<dyn trait> It depends on trait. It's only Send because the IcebergWriter trait is only Send. Do we need Sync here?🤔

**Comment by liurenjie1024** [comment]
> > Is DeltaWriter  and RecordBatchWriter written in this approach can be Send + Sync?
> 
> Send and Sync in Box It depends on trait. It's only Send because the IcebergWriter trait is only Send. Do we need Sync here?🤔

I'm not sure if we need `Sync`, but from risingwave's use case we only need to be `Send`. cc @Xuanwo

**Comment by Xuanwo** [comment]
> but from risingwave's use case we only need to be `Send`

all APIs in `Writer` takes `&mut self`, requiring `Send` is enough.

**Comment by ZENOTME** [comment]
I realized that one more point: close(&mut self) is different than close(self), it means that a writer should consider the case that it will be reuse after close. Actually it's more like `flush(&mut self)`. In some case, this may make the writer more complete, e.g. 
1. delta writer will maintain the cache, and it should clear the cache when flush.
2. rolling writer should open a new writer when flush.
But I find that we can't use `close(self)` instead because we can't move the value in `Box<dyn Writer>` 🥵

**Comment by Xuanwo** [comment]
> it means that a writer should consider the case that it will be reuse after close.

Calling close in the same writer should return an error.

**Comment by ZENOTME** [comment]
> Calling close multiple on the same writer should return an error. 

This is an approach. But I'm not sure whether it will add the extra maintain effort. We need add check for each interface such as write. 🤔

**Comment by liurenjie1024** [comment]
> I realized that one more point: `close(&mut self)` is different than close(self), it means that a writer should consider the case that it will be reuse after close. Actually it's more like `flush(&mut self)`. In some case, this may make the writer more complete, e.g.
> 
> 1. delta writer will maintain the cache, and it should clear the cache when flush.
> 2. rolling writer should open a new writer when flush.
> 
> But I find that we can't use `close(self)` instead because we can't move the value in `Box<dyn Writer>` 🥵

How about `close(Box<Self>)`?

**Comment by Xuanwo** [comment]
> This is an approach. But I'm not sure whether it will add the extra maintain effort. We need add check for each interface such as write. 🤔

You can just passing `close` to underlying layer, a.k.a, let opendal handle those work.

**Comment by liurenjie1024** [comment]
> > This is an approach. But I'm not sure whether it will add the extra maintain effort. We need add check for each interface such as write. 🤔
> 
> We can just passing `close` to underlying layer, a.k.a, let opendal handle those work.

I guess the problem is api safety.

**Comment by liurenjie1024** [comment]
> > I guess the problem is api safety.
> 
> I feel like it's the same problem like calling `poll` while this future returns `Poll::Ready` (calling `close` while this file has already closed):
> 
> > Once a future has completed (returned Ready from poll), calling its poll method again may panic, block forever, or cause other kinds of problems; the Future trait places no requirements on the effects of such a call. However, as the poll method is not marked unsafe, Rust’s usual rules apply: calls must never cause undefined behavior (memory corruption, incorrect use of unsafe functions, or the like), regardless of the future’s state.
> 
> from https://doc.rust-lang.org/std/future/trait.Future.html

Yes, it's hard to ensure everything safe. We should try as much as possible 😂

**Comment by ZENOTME** [comment]
> How about close(Box<Self>)?

Fail. Because it need to `Self: Sized` and that will make the trait is not object-safe.

**Comment by ZENOTME** [comment]
> > I guess the problem is api safety.
> 
> I feel like it's the same problem like calling `poll` while this future returns `Poll::Ready` (calling `close` while this file has already closed):
> 
> > Once a future has completed (returned Ready from poll), calling its poll method again may panic, block forever, or cause other kinds of problems; the Future trait places no requirements on the effects of such a call. However, as the poll method is not marked unsafe, Rust’s usual rules apply: calls must never cause undefined behavior (memory corruption, incorrect use of unsafe functions, or the like), regardless of the future’s state.
> 
> from https://doc.rust-lang.org/std/future/trait.Future.html

Yes. We can define that after close, call close or write will panic. But to satisfy it, we need to set the check in write and close for every writer.  Such as 
```
fn write() {
  if (self.is_close) {
    panic()
  }
}
```

**Comment by ZENOTME** [comment]
The new writer is done! Thanks for your help and suggestions! @Xuanwo @liurenjie1024
