### ISSUE TITLE
Pin Arrow Dependency Version

### ISSUE THREAD

**Issue by xxhZs** [icelake-io/icelake#249]
I realized that icelake's arrow dependency is automatically pulling the latest version, but icelake's code doesn't seem to use the latest version, so is it possible to fix the arrow version. 
The reason for this request is that my project uses another package that depends on arrow, and icelake's current dependency implementation prevents me from fixing icelake or other dependencies in my project, which prevents me from reusing some of my methods.

**Comment by Xuanwo** [comment]
Duplicated to https://github.com/icelake-io/icelake/discussions/234
