### ISSUE TITLE
Can we support custom split logic for `RollingWriter`

### ISSUE THREAD

**Issue by nooberfsh** [icelake-io/icelake#256]
`RollingWriter::should_split` split arrow writer based some configs which have some limitation, e.g. when user want split the arrow writer after the current row num >= 1000.

Can we provide an API like this:
```rust
pub WriteStats {
    current_row_num: usize,
    current_written_size: usize,
}

impl RollingWriterBuilder {
    fn with_split(mut self, split_f: impl Fn(&WriteStats) -> bool) -> Self {
        ...
    }
}
```

**Comment by ZENOTME** [comment]
Actually the user can custom their own file writer. But I think that it's a good suggestion. How do you think? @liurenjie1024

**Comment by liurenjie1024** [comment]
It's ok to me to have a pluggable split policy.

**Comment by Xuanwo** [comment]
Closing for https://github.com/icelake-io/icelake/issues/279
