### ISSUE TITLE
Improve project charter

### ISSUE THREAD

**Issue by romusz** [icelake-io/icelake#262]
Hello there,

Happy to see Rust community getting into Iceberg.
To help deciding between Icelake, iceberg-rust, and Iceberg-rs, would you mind clarifying how those 3 differ:
 - would your project provide just a reader and writer of Iceberg files (manifest, manifest lists, metadata) or also include integrations with processing and query engines? If so, which ones are considered?
 - is implementation of Iceberg REST catalog in scope for your project?

Thanks a lot!

**Comment by Xuanwo** [comment]
> To help deciding between Icelake, iceberg-rust, and Iceberg-rs, would you mind clarifying how those 3 differ:

All contributors from `icelake` and `iceberg-rs` have united under `iceberg-rust`. Our shared objective is to develop Iceberg Rust upstream. Ultimately, we aim to integrate all existing features of `icelake` into `iceberg-rust`.

> would your project provide just a reader and writer of Iceberg files (manifest, manifest lists, metadata) or also include integrations with processing and query engines? If so, which ones are considered?

For now, we only have reader and writer support. And in the future, we might provide native datafusion support.

> is implementation of Iceberg REST catalog in scope for your project?

Yes, of course. We have implemented REST catalog both in icelake and iceberg-rust. 

---

We recommand you take a look over iceberg-rust first. We are working on iceberg-rust's first release. Welcome to join the development!

**Comment by Xuanwo** [comment]
Closing for https://github.com/icelake-io/icelake/issues/279
