### ISSUE TITLE
Feat: expose file's sequence number for interface data_files_of_snapshot

### ISSUE THREAD

**Issue by chenzl25** [icelake-io/icelake#273]
Currently, `data_files_of_snapshot` returns a vector of `DataFile` which lacks sequence number information, so it can't be used to support MOR table scan. Any plan for a better interface?
```rust
pub async fn data_files_of_snapshot(
        &self,
        snapshot: &Snapshot,
    ) -> Result<Vec<types::DataFile>>
```

**Comment by Xuanwo** [comment]
Closing for https://github.com/icelake-io/icelake/issues/279
