### ISSUE TITLE
publish forked avro and then publish new icelake version

### ISSUE THREAD

**Issue by xxchan** [icelake-io/icelake#275]
The main reason: avro's git is very very large, including these submodules... So when we git depends on icelake, we need to pull all these stuff from git..

<img width="491" alt="image" src="https://github.com/icelake-io/icelake/assets/37948597/dd026d4a-f48c-4576-8915-967c788da30b">

cc @Xuanwo

**Comment by xxchan** [comment]
Oh, a lower effort is simply remove the submodule from the avro fork https://github.com/risingwavelabs/avro/commit/5af26339d28cedec8455abb811150ab020d4330d

**Comment by Xuanwo** [comment]
> Oh, a lower effort is simply remove the submodule from the avro fork [risingwavelabs/avro@5af2633](https://github.com/risingwavelabs/avro/commit/5af26339d28cedec8455abb811150ab020d4330d)

Makes sense to me, would you like to submit a PR?

By the way, icelake will be replaced by iceberg-rust. I encourage you to start planning for this transition. Once iceberg-rust covers all features that icelake provided, we will deprecate this crate.

**Comment by xxchan** [comment]
Yes, we are planning for the transition. BTW, my original problem (pulling git dependencies in CI is slow) is solved by caching cargo registry, so I'm not worried any more :p https://github.com/risingwavelabs/risingwave/pull/16909
