### ISSUE TITLE
`TrackWriter` return incorrect `written_size`

### ISSUE THREAD

**Issue by nooberfsh** [icelake-io/icelake#278]
```rust
#[tokio::main]
async fn main() -> Result<()> {
    let wsize = Arc::new(AtomicI64::new(0));
    let mut w = make_writer(wsize.clone()).await?;

    let data = "hello, opendal";
    for _ in 0..1_000_000 {
        w.write_all(data.as_bytes()).await?
    }

    w.shutdown().await?;
    let wsize = wsize.load(std::sync::atomic::Ordering::SeqCst);
    println!("written size: {wsize}");

    Ok(())
}

async fn make_writer(wsize: Arc<AtomicI64>) -> Result<TrackWriter> {
    let mut builder = Fs::default();
    builder.root(".");
    let op: Operator = Operator::new(builder)?.finish();

    let w = op
        .writer("test.txt")
        .await
        .unwrap()
        .into_futures_async_write();
    Ok(TrackWriter::new(w, wsize))
}

```
Full code can be found in this [repo](https://github.com/nooberfsh/icelake_track_writer)

The above code write a simple string literal "hello, opendal" to local file test.txt 1_000_000 times using `TrackWriter`.
The expected written_size should be 14000000, but the above code print 14000326 on my machine which does not match the file size.

Related code:
 https://github.com/icelake-io/icelake/blob/07d53893d7788b4e41fc11efad8a6be828405c31/icelake/src/io_v2/file_writer/track_writer.rs#L30-L33

**Comment by Xuanwo** [comment]
Closing for https://github.com/icelake-io/icelake/issues/279
