### ISSUE TITLE
Ignore Cargo.lock in git?

### ISSUE THREAD

**Issue by TennyZhuang** [icelake-io/icelake#29]
It's recommended in https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html

> If you’re building a non-end product, such as a rust library that other rust [packages](https://doc.rust-lang.org/cargo/appendix/glossary.html#package) will depend on, put Cargo.lock in your .gitignore.

**Comment by Xuanwo** [comment]
Makes sense, let's do this.
