### ISSUE TITLE
Tracking: Implement table transaction api.

### ISSUE THREAD

**Issue by liurenjie1024** [icelake-io/icelake#39]
A table transaction is a collection of modifications to an iceberg table, we can support them one by one.

- [x] Support append files in transaction.
- [x] Support row delta in transaction.

We can have following as reference:

https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/Transaction.java
https://github.com/risingwavelabs/iceberg-rust/blob/main/iceberg-rust/src/table/transaction/mod.rs

**Comment by xxhZs** [comment]
can i do it?
