### ISSUE TITLE
Introduce error type for io module

### ISSUE THREAD

**Issue by ZENOTME** [icelake-io/icelake#52]
We can introduce two error type like 
```
`For io module`
enum IoError {
    Appender(AppenderError)
}

// For `ParquetWriter`
struct AppenderError {}
```
@Xuanwo @liurenjie1024 What do you think?

**Comment by Xuanwo** [comment]
For error handling, we need to the following things:

- Error code that help users to decide how to take actions.
- Error Message that describe what happend.
- Error Context that provide more information for users.
- Error Causes that help users to figure out what happened (with backtrace support).

An error enum is not a good idea to me. I will start a PR for this.
