### ISSUE TITLE
Expose metrics to users.

### ISSUE THREAD

**Issue by liurenjie1024** [icelake-io/icelake#58]
As a library, we should be able to expose metrics to external users for better observability. Any suggestions?

**Comment by Xuanwo** [comment]
Nice idea! We should provide observability features such as logging, tracing, and metrics for our users. I suggest we begin working on this after our API is almost ready for use.

**Comment by Xuanwo** [comment]
My another project [opendal](https://github.com/apache/incubator-opendal) provides support for all of [metrics](https://docs.rs/metrics/), [prometheus](https://docs.rs/prometheus). Most users prefer to use prometheus directly.
