### ISSUE TITLE
Implement append only task writer.

### ISSUE THREAD

**Issue by liurenjie1024** [icelake-io/icelake#74]
An append-only task writer accepts an optional partitioner, file appender factory as arguments. When it receives records, it dispatches records to different file writer according to the partition key(generated by partitioner), and inserts it. When it finished, it returns generated data file structs. 

Notice that this will be the api used directly by compute engines such as risingwave, ballista. We can refer to following implementation as an example.

https://github.com/apache/iceberg/blob/e340ad5be04e902398c576f431810c3dfa4fe717/core/src/main/java/org/apache/iceberg/io/PartitionedFanoutWriter.java#L28

**Comment by Xuanwo** [comment]
> How did this api used to by compute engines?

Let's prioritize making it functional for now and refine the API later.

**Comment by ZENOTME** [comment]
This issue can be close now

**Comment by ZENOTME** [comment]
I realize that in future we need to add position delete file writer, and the user can use like following (use different writer seperately):

```
// Create a writer to write data file
let append_writer = table.append_writer();
append_writer.write();
let delete_writer = table.delete_writer();
delete_writer.write();

let append_data_files = append_writer.close();
let delete_data_files = delete_writer.close();

// apply these data file to the table
let tx = table.transaction;
tx.apply(append_data_files);
tx.commit();

// apply these data file to the table
let tx = table.transaction;
tx.apply(delete_data_files);
tx.commit();
```

So maybe name the interface be append_writer() will be better?

**Comment by Xuanwo** [comment]
Closing for https://github.com/icelake-io/icelake/issues/279
