### ISSUE TITLE
discussion: sync with the apache Iceberg community

### ISSUE THREAD

**Issue by neverchanje** [icelake-io/icelake#83]
Hi there,

There is a thread regarding the C++/Rust support for Iceberg in the community's dev mail list. Here is the link: https://lists.apache.org/thread/7njzq6b0m9qbjmbtgrtkhmj2nnmhso4t I wonder if you fellows can reply to this thread and ask for the feedbacks from the Iceberg community? I think most community members would welcome this project. However, there will be a lot to discuss in terms of the technical design, in which you may need the professional advice from the community. With the advice and feedbacks, we will be able to see if this project is heading towards the right direction.

**Comment by Xuanwo** [comment]
Great idea! Of course, we need to synchronize with the Apache Iceberg community. However, asking for feedback at this stage may not be a good idea. We need to shape our project and make it work first.
